name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test, Lint and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          check-latest: true

      - name: Dependencies 
        run: |
          go mod verify
          go mod tidy
          git diff --exit-code # Ensures go.mod and go.sum are up to date

      - name: Run Tests 
        run: |
          go test -v -race -shuffle=on ./...

      - name: Run golangci-lint manually
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --timeout=10m

